"""
setup_geosam_session.py
-----------------------
Run in the QGIS Python Console, once per session and whenever you want to
switch species:

    exec(open('<REPO>/qgis/setup_geosam_session.py').read())
    setup(species='Sphagnum_R')

What it does:
  1. Loads the orthomosaic and EVERY species layer of the site, each in its
     own colour.
  2. Binds Geo-SAM to the species layer you picked.
  3. Puts that layer into edit mode.
  4. Installs a hook: from then on, just CLICK a layer in the Layers panel and
     Geo-SAM follows it. No need to call setup() again.

ONE LAYER PER SPECIES: the layer name IS the species, so there is no attribute
to fill in when you draw.

The order Geo-SAM requires (getting it wrong fails SILENTLY)
------------------------------------------------------------
1. The layer must carry the FULL Geo-SAM field set (group_ulid, N_GM, id, Area,
   N_FG, N_BG, BBox, lb_name, lb_note). Miss one and you get "The fields of
   this vector do not match the SAM feature fields".
   scripts/init_labels_gpkg.py creates them with the right schema.
2. The IMAGE SOURCE must be set BEFORE the annotation layer.
   set_vector_layer() returns immediately when img_crs_manager does not exist
   yet - no log, no exception.
3. Never set the annotation combo box to None first. Any trip through None
   drags set_vector_layer -> reset_layer(None) -> _init_layer(), which calls
   addAttributes unconditionally and raises "field already exists".
4. scripts/patch_geosam_fields.py must have been run once on this machine.
   Without it Geo-SAM writes attributes BY COLUMN POSITION and your polygon
   vanishes when you press S.
"""
import os

from qgis.core import (QgsProject, QgsRasterLayer, QgsSingleSymbolRenderer,
                       QgsSymbol, QgsVectorLayer, QgsWkbTypes)
from qgis.PyQt.QtGui import QColor
from qgis.utils import plugins

# ---------------------------------------------------------------- config
# Do NOT edit this file to run it on another machine. Set these once per QGIS
# session, before running any script (see README.md):
#
#   import qgis.utils
#   qgis.utils.BV_REPO   = r'D:\path\to\segmentation_model'
#   qgis.utils.BV_SITE   = 'site_name'
#   qgis.utils.BV_PYTHON = r'C:\...\envs\bunjilview\python.exe'   # optional
#
# Leave BV_PYTHON unset and the scripts read it from
# data/labels/<site>/site.json.
DEFAULT_REPO = '/Users/huydinh/Desktop/Home/Bunjilview/segmentation_model'
DEFAULT_SITE = 'test1'
DEFAULT_PYTHON = '/opt/homebrew/Caskroom/miniconda/base/envs/bunjilview/bin/python'


def _cfg():
    import json
    import qgis.utils as _qu
    repo = (getattr(_qu, 'BV_REPO', '') or DEFAULT_REPO).rstrip('/\\')
    site = getattr(_qu, 'BV_SITE', '') or DEFAULT_SITE
    py = getattr(_qu, 'BV_PYTHON', '')
    if not py:
        sj = os.path.join(repo, 'data', 'labels', site, 'site.json')
        if os.path.isfile(sj):
            try:
                py = json.load(open(sj)).get('venv_python', '') or ''
            except Exception:
                py = ''
    return repo, site, (py or DEFAULT_PYTHON)


REPO, SITE, VENV_PYTHON = _cfg()

SPECIES = 'Poa_costiniana'        # default species when setup() is called bare

# Colours picked to stand out on drone imagery: no greens, no earth browns.
PALETTE = {
    'Empidisma_minus':          '#e6194b',   # crimson
    'Dracophyllum_continentis': '#f58231',   # orange
    'Poa_costiniana':           '#ffe119',   # yellow
    'Carex_gaudichaudiana':     '#42d4f4',   # cyan
    'Celmisia_pugioniformis':   '#fabed4',   # pink
    'Sphagnum_R':               '#911eb4',   # purple
    'Sphagnum_G':               '#4363d8',   # blue
    'Sphagnum_Y':               '#ffffff',   # white
    'Other':                    '#a9a9a9',   # grey
}
CYCLE = ['#e6194b', '#f58231', '#ffe119', '#42d4f4', '#fabed4',
         '#911eb4', '#4363d8', '#ffffff', '#a9a9a9', '#dcbeff']

GEOSAM_FIELDS = ['group_ulid', 'N_GM', 'id', 'Area', 'N_FG', 'N_BG', 'BBox',
                 'lb_name', 'lb_note']
BUNJIL_FIELDS = ['species', 'source', 'score', 'run_ts']


def _species_names(repo):
    import yaml
    with open(os.path.join(repo, 'config.yaml')) as f:
        cfg = yaml.safe_load(f)
    return [v for _, v in sorted(cfg['classes'].items(), key=lambda kv: int(kv[0]))
            if v and v != 'None']


def _color_for(name, names):
    if name in PALETTE:
        return PALETTE[name]
    return CYCLE[names.index(name) % len(CYCLE)] if name in names else '#ff00ff'


def _style(layer, hex_color):
    """Single symbol only. Geo-SAM calls renderer().setSymbol(), which exists
    only on a single-symbol renderer, so never use a categorized one here."""
    sym = QgsSymbol.defaultSymbol(QgsWkbTypes.PolygonGeometry)
    fill = QColor(hex_color)
    fill.setAlpha(70)
    sym.setColor(fill)
    sl = sym.symbolLayer(0)
    sl.setStrokeColor(QColor(hex_color))
    sl.setStrokeWidth(0.5)
    layer.setRenderer(QgsSingleSymbolRenderer(sym))
    layer.triggerRepaint()


def _bind(sel, ras, target, say):
    """Bind Geo-SAM to `target`. Image source FIRST, annotation layer SECOND."""
    wdg = sel.wdg_sel

    # Commit anything unsaved on the previous layer so no work is lost.
    old = sel.polygon.get_layer() if hasattr(sel, 'polygon') else None
    if old is not None and old.id() != target.id() and old.isEditable():
        if old.isModified():
            old.commitChanges()
            say('committed pending edits on %r' % old.name())
        else:
            old.rollBack()

    # Image source: activate ONCE. Re-running it calls clear_layers and rebuilds
    # the runtime, which is slow and pointless.
    if not hasattr(sel, 'img_crs_manager'):
        wdg.LiveEncodingLayerComboBox.setLayer(ras)
        sel.on_live_encoding_layer_changed()
    if not hasattr(sel, 'img_crs_manager'):
        raise RuntimeError('img_crs_manager was not created, the image source '
                           'did not activate')

    # Do NOT setLayer(None) first. Any trip through None drags
    # set_vector_layer -> reset_layer(None) -> _init_layer(), which calls
    # addAttributes unconditionally -> "field already exists".
    # Set it directly and call set_vector_layer() by hand: it reads
    # currentLayer(), it does not need the signal.
    wdg.MapLayerComboBox.setLayer(target)
    sel.set_vector_layer()
    if not hasattr(sel, 'polygon'):
        raise RuntimeError('Geo-SAM failed to bind the layer')
    return sel.polygon.get_layer()


def _install_hook(repo, gpkg, names, ras, sel, say):
    """Click a layer in the Layers panel -> Geo-SAM switches to it."""
    import qgis.utils
    from qgis.utils import iface

    view = iface.layerTreeView()
    prev = getattr(qgis.utils, '_bunjilview_layer_hook', None)
    if prev is not None:
        try:
            view.currentLayerChanged.disconnect(prev)
        except Exception:
            pass

    def on_changed(lyr):
        try:
            if lyr is None or lyr.name() not in names or gpkg not in lyr.source():
                return
            if hasattr(sel, 'polygon'):
                cur = sel.polygon.get_layer()
                if cur is not None and cur.id() == lyr.id():
                    return
            _bind(sel, ras, lyr, lambda m: None)
            _style(lyr, _color_for(lyr.name(), names))
            if not lyr.isEditable():
                lyr.startEditing()
            iface.messageBar().pushInfo(
                'Geo-SAM', 'switched to layer %s' % lyr.name())
        except Exception as e:
            iface.messageBar().pushWarning(
                'Geo-SAM', 'could not switch to %s: %s'
                % (lyr.name() if lyr else '?', e))

    view.currentLayerChanged.connect(on_changed)
    qgis.utils._bunjilview_layer_hook = on_changed
    say('hook installed: clicking a layer in the Layers panel switches Geo-SAM')


def setup(repo=REPO, site=SITE, species=SPECIES, verbose=True):
    say = (lambda m: print(m)) if verbose else (lambda m: None)
    proj = QgsProject.instance()
    gpkg = os.path.join(repo, 'data/labels', site, site + '.gpkg')
    ortho = os.path.join(repo, 'data/raw', site + '.tif')
    if not os.path.isfile(gpkg):
        raise RuntimeError('%s not found. Run scripts/init_labels_gpkg.py first.'
                           % gpkg)

    names = _species_names(repo)
    if species not in names:
        raise RuntimeError("'%s' is not in config.yaml `classes`. Available: %s"
                           % (species, ', '.join(names)))

    # -- load every species layer, each in its own colour --
    loaded = {}
    for name in names:
        lyr = next((l for l in proj.mapLayers().values()
                    if l.name() == name and gpkg in l.source()), None)
        if lyr is None:
            lyr = QgsVectorLayer(gpkg + '|layername=' + name, name, 'ogr')
            if not lyr.isValid():
                say('  skipping %s (could not open)' % name)
                continue
            proj.addMapLayer(lyr)
        _style(lyr, _color_for(name, names))
        loaded[name] = lyr
    say('loaded %d species layers, one colour each' % len(loaded))

    target = loaded.get(species)
    if target is None:
        raise RuntimeError("could not open layer '%s' in %s" % (species, gpkg))

    missing = [f for f in GEOSAM_FIELDS + BUNJIL_FIELDS
               if f not in [x.name() for x in target.fields()]]
    if missing:
        raise RuntimeError("layer '%s' is missing fields %r. Re-run "
                           "scripts/init_labels_gpkg.py." % (species, missing))
    say("layer '%s': %d fields, %d features"
        % (species, len(target.fields()), target.featureCount()))

    # -- orthomosaic --
    ras = next((l for l in proj.mapLayers().values() if l.name() == site), None)
    if ras is None and os.path.isfile(ortho):
        ras = QgsRasterLayer(ortho, site)
        if ras.isValid():
            proj.addMapLayer(ras)
            say('loaded orthomosaic %s' % ortho)
    if ras is None:
        raise RuntimeError('no raster layer %r in the project and %s does not exist'
                           % (site, ortho))

    # -- plugin --
    geo = plugins.get('GeoSAM')
    if geo is None:
        raise RuntimeError('the GeoSAM plugin is not loaded')
    if getattr(geo, 'wdg_select', None) is None:
        geo.create_widget_selector()
        say('opened the Geo-SAM selector')
    sel = geo.wdg_select

    bound = _bind(sel, ras, target, say)
    say('image source active')
    say("Geo-SAM bound to '%s' (%d features)"
        % (bound.name() if bound else None, bound.featureCount() if bound else -1))

    # Re-apply the colours AFTER binding: Geo-SAM's show_layer() calls
    # addMapLayer and overwrites the renderer, so styling before binding is
    # wasted work.
    for name, lyr in loaded.items():
        _style(lyr, _color_for(name, names))
    say('re-applied colours to %d layers after binding' % len(loaded))

    try:
        from qgis.utils import iface
        iface.setActiveLayer(target)
        if not target.isEditable():
            target.startEditing()
        say('active layer = %s | editable = %s'
            % (target.name(), target.isEditable()))
    except Exception as e:
        say('could not enable edit mode: %r' % e)

    # Move the orthomosaic to the bottom and zoom to it while there are no
    # polygons yet. An empty layer has an empty extent, so QGIS has nothing to
    # frame, the canvas stays at planet scale and the ortho is smaller than one
    # pixel - which looks exactly like a missing image.
    try:
        from qgis.utils import iface
        root = proj.layerTreeRoot()
        node = root.findLayer(ras.id())
        if node is not None:
            if not node.isVisible():
                node.setItemVisibilityChecked(True)
            if root.children() and root.children()[-1] is not node:
                root.insertChildNode(-1, node.clone())
                root.removeChildNode(node)
        has_polygons = any(l.featureCount() > 0 for l in loaded.values())
        if not has_polygons:
            iface.mapCanvas().setDestinationCrs(ras.crs())
            iface.mapCanvas().setExtent(ras.extent())
            iface.mapCanvas().refresh()
            say('no polygons yet -> zoomed to the orthomosaic')
        else:
            say('polygons present, leaving the current view alone')
    except Exception as e:
        say('could not zoom to the orthomosaic: %r' % e)

    _install_hook(repo, gpkg, names, ras, sel, say)

    say("\nReady. Draw a seed for '%s', press S, then run "
        "Scripts > Bunjilview > Propagate species from seed and pick this same "
        "layer." % species)
    say('To switch species: CLICK that layer in the Layers panel.')
    return sel


try:
    selector = setup()
except Exception as exc:
    print('SETUP FAILED: %s' % exc)
