"""
setup_geosam_session.py
-----------------------
Run in the QGIS Python Console, once per session and whenever you want to
switch species:

    exec(open('<REPO>/qgis/setup_geosam_session.py').read())
    setup(species='Sphagnum')

What it does:
  1. Loads the orthomosaic and EVERY species layer of the site, each in its
     own colour.
  2. Binds Geo-SAM to the species layer you picked.
  3. Puts that layer into edit mode.
  4. Installs a hook: from then on, just CLICK a layer in the Layers panel and
     Geo-SAM follows it. No need to call setup() again.

ONE LAYER PER SPECIES: the layer name IS the species, so there is no attribute
to fill in when you draw.

The order Geo-SAM requires (getting it wrong fails SILENTLY)
------------------------------------------------------------
1. The layer must carry the FULL Geo-SAM field set (group_ulid, N_GM, id, Area,
   N_FG, N_BG, BBox, lb_name, lb_note). Miss one and you get "The fields of
   this vector do not match the SAM feature fields".
   scripts/init_labels_gpkg.py creates them with the right schema.
2. The IMAGE SOURCE must be set BEFORE the annotation layer.
   set_vector_layer() returns immediately when img_crs_manager does not exist
   yet - no log, no exception.
3. Never set the annotation combo box to None first. Any trip through None
   drags set_vector_layer -> reset_layer(None) -> _init_layer(), which calls
   addAttributes unconditionally and raises "field already exists".
4. scripts/patch_geosam_fields.py must have been run once on this machine.
   Without it Geo-SAM writes attributes BY COLUMN POSITION and your polygon
   vanishes when you press S.
"""
import os

from qgis.core import (QgsProject, QgsRasterLayer, QgsSingleSymbolRenderer,
                       QgsSymbol, QgsVectorLayer, QgsWkbTypes)
from qgis.PyQt.QtGui import QColor
from qgis.utils import plugins

# ---------------------------------------------------------------- config
# Do NOT edit this file to run it on another machine. Set these once per QGIS
# session, before running any script (see README.md):
#
#   import qgis.utils
#   qgis.utils.BV_REPO   = r'D:\path\to\segmentation_model'
#   qgis.utils.BV_SITE   = 'site_name'
#   qgis.utils.BV_PYTHON = r'C:\...\envs\bunjilview\python.exe'   # optional
#
# Leave BV_PYTHON unset and the scripts read it from
# data/labels/<site>/site.json.
DEFAULT_REPO = '/Users/huydinh/Desktop/Home/Bunjilview/segmentation_model'
DEFAULT_SITE = 'test1'
DEFAULT_PYTHON = '/opt/homebrew/Caskroom/miniconda/base/envs/bunjilview/bin/python'


def _cfg():
    import json
    import qgis.utils as _qu
    repo = (getattr(_qu, 'BV_REPO', '') or DEFAULT_REPO).rstrip('/\\')
    site = getattr(_qu, 'BV_SITE', '') or DEFAULT_SITE
    py = getattr(_qu, 'BV_PYTHON', '')
    if not py:
        sj = os.path.join(repo, 'data', 'labels', site, 'site.json')
        if os.path.isfile(sj):
            try:
                py = json.load(open(sj)).get('venv_python', '') or ''
            except Exception:
                py = ''
    return repo, site, (py or DEFAULT_PYTHON)


REPO, SITE, VENV_PYTHON = _cfg()

SPECIES = None                    # None = first species in config.yaml

# Colours picked to stand out on drone imagery: no greens, no earth browns.
PALETTE = {
    'Empidisma_minus':          '#e6194b',   # crimson
    'Dracophyllum_continentis': '#f58231',   # orange
    'Poa_costiniana':           '#ffe119',   # yellow
    'Carex_gaudichaudiana':     '#42d4f4',   # cyan
    'Celmisia_pugioniformis':   '#fabed4',   # pink
    'Sphagnum':                 '#911eb4',   # purple
    'Sphagnum_R':               '#911eb4',   # purple  (older sites that split it)
    'Sphagnum_G':               '#4363d8',   # blue
    'Sphagnum_Y':               '#ffffff',   # white
    'Other':                    '#a9a9a9',   # grey
}
CYCLE = ['#e6194b', '#f58231', '#ffe119', '#42d4f4', '#fabed4',
         '#911eb4', '#4363d8', '#ffffff', '#a9a9a9', '#dcbeff']

GEOSAM_FIELDS = ['group_ulid', 'N_GM', 'id', 'Area', 'N_FG', 'N_BG', 'BBox',
                 'lb_name', 'lb_note']
BUNJIL_FIELDS = ['species', 'source', 'score', 'run_ts']


def _species_names(repo):
    import yaml
    with open(os.path.join(repo, 'config.yaml')) as f:
        cfg = yaml.safe_load(f)
    return [v for _, v in sorted(cfg['classes'].items(), key=lambda kv: int(kv[0]))
            if v and v != 'None']


def _color_for(name, names):
    if name in PALETTE:
        return PALETTE[name]
    return CYCLE[names.index(name) % len(CYCLE)] if name in names else '#ff00ff'


def _style(layer, hex_color):
    """Single symbol only. Geo-SAM calls renderer().setSymbol(), which exists
    only on a single-symbol renderer, so never use a categorized one here."""
    sym = QgsSymbol.defaultSymbol(QgsWkbTypes.PolygonGeometry)
    fill = QColor(hex_color)
    fill.setAlpha(70)
    sym.setColor(fill)
    sl = sym.symbolLayer(0)
    sl.setStrokeColor(QColor(hex_color))
    sl.setStrokeWidth(0.5)
    layer.setRenderer(QgsSingleSymbolRenderer(sym))
    layer.triggerRepaint()


def _norm(path):
    """Comparable form of a path: normalised separators, case-folded on Windows."""
    return os.path.normcase(os.path.normpath(str(path)))


def _layer_gpkg(layer):
    """The GeoPackage path behind an OGR layer, without the |layername= part."""
    try:
        return _norm(layer.source().split('|')[0])
    except RuntimeError:
        return ''


def _is_site_layer(layer, gpkg):
    """True when `layer` comes from `gpkg`, however the path was spelled.

    Substring matching on the raw source string breaks on Windows: this script
    builds paths with os.path.join (backslashes) while layers added through
    the QGIS GUI carry forward slashes, so the same file never matched and
    every layer was loaded a second time.
    """
    return _layer_gpkg(layer) == _norm(gpkg)


def _live_raster(name, fallback=None):
    """The orthomosaic layer currently in the project, looked up by NAME.

    Never cache a QgsRasterLayer across calls. When a layer is removed from the
    project QGIS deletes the C++ object, and the Python wrapper left behind
    raises "wrapped C/C++ object of type QgsRasterLayer has been deleted" the
    next time anything touches it. Names are plain strings, so they never go
    stale.
    """
    for lyr in QgsProject.instance().mapLayers().values():
        try:
            if lyr.name() == name and isinstance(lyr, QgsRasterLayer):
                lyr.crs().authid()          # touches the C++ object
                return lyr
        except RuntimeError:
            continue
    return fallback


def _forget_dead_raster(sel):
    """Set every plugin attribute that holds a deleted QgsRasterLayer to None.

    Geo-SAM keeps the live-encoding raster in `runtime_layer` and reads it on
    every FG click. Once that C++ object is gone, any call on it raises, so
    the reference has to be cleared before the plugin can activate a new one.
    Returns True when something was cleared.
    """
    try:
        from qgis.PyQt import sip
    except ImportError:
        import sip
    cleared = False
    for obj in (sel, getattr(sel, 'img_crs_manager', None)):
        if obj is None:
            continue
        try:
            items = list(vars(obj).items())
        except TypeError:
            continue
        for key, val in items:
            if isinstance(val, QgsRasterLayer):
                try:
                    dead = sip.isdeleted(val)
                except RuntimeError:
                    dead = True
                if dead:
                    setattr(obj, key, None)
                    cleared = True
    return cleared


def _image_source_alive(sel, ras):
    """True when Geo-SAM's image source is live AND points at `ras`.

    hasattr(sel, 'img_crs_manager') alone is not enough: the attribute survives
    after the raster it was built from has been deleted, and Geo-SAM then fails
    inside prepare_realtime_raster_query with a deleted-object RuntimeError the
    moment you press FG.
    """
    if not hasattr(sel, 'img_crs_manager'):
        return False
    try:
        cur = sel.wdg_sel.LiveEncodingLayerComboBox.currentLayer()
        if cur is None or ras is None or cur.id() != ras.id():
            return False
        cur.crs().authid()
        ras.crs().authid()
    except RuntimeError:
        return False
    # The combo box drops deleted layers on its own, so it can look healthy
    # while the plugin still holds the old wrapper: execute_segmentation()
    # reads self.runtime_layer, never the combo. Check that one explicitly,
    # then walk the rest of the plugin's attributes for any other raster.
    try:
        from qgis.PyQt import sip
    except ImportError:            # older QGIS builds
        import sip
    rt = getattr(sel, 'runtime_layer', None)
    if rt is None:
        return False
    try:
        if sip.isdeleted(rt) or rt.id() != ras.id():
            return False
    except RuntimeError:
        return False
    holders = [sel, getattr(sel, 'img_crs_manager', None)]
    for obj in holders:
        if obj is None:
            continue
        try:
            attrs = vars(obj)
        except TypeError:
            continue
        for val in attrs.values():
            if isinstance(val, QgsRasterLayer):
                try:
                    if sip.isdeleted(val) or val.id() != ras.id():
                        return False
                except RuntimeError:
                    return False
    return True


def _pre_encoded_mode(sel):
    """True when the Geo-SAM panel's source dropdown is on "Pre-encoded".

    Geo-SAM 2 segments either from Live Encoding (encodes a chip around every
    click, slow on CPU) or from a feature folder made once by its Image
    Encoder. The plugin exposes no attribute for the mode, so read the
    dropdown: the combo box whose items include both "Live Encoding" and
    "Pre-encoded". Unknown layout -> False, i.e. the live-encoding handling
    below runs as before.
    """
    try:
        from qgis.PyQt.QtWidgets import QComboBox
        for cb in sel.wdg_sel.findChildren(QComboBox):
            items = [cb.itemText(i).lower() for i in range(cb.count())]
            if any('pre-encoded' in t or 'pre_encoded' in t for t in items) \
                    and any('live' in t for t in items):
                return 'pre' in cb.currentText().lower()
    except Exception:
        pass
    return False


def _bind(sel, ras, target, say):
    """Bind Geo-SAM to `target`. Image source FIRST, annotation layer SECOND.

    In Pre-encoded mode the image source is the feature folder the user
    loaded in the panel; touching the live-encoding combo would flip the
    plugin back to live mode, so only the annotation layer is bound then.
    """
    wdg = sel.wdg_sel
    pre_encoded = _pre_encoded_mode(sel)

    # Commit anything unsaved on the previous layer so no work is lost.
    try:
        old = sel.polygon.get_layer() if hasattr(sel, 'polygon') else None
        if old is not None and old.id() != target.id() and old.isEditable():
            if old.isModified():
                old.commitChanges()
                say('committed pending edits on %r' % old.name())
            else:
                old.rollBack()
    except RuntimeError:
        pass                # the previous layer was deleted: nothing to save

    # Image source: activate when it is missing OR stale. Re-running it calls
    # clear_layers and rebuilds the runtime, which is slow, so do not do it on
    # every bind - but a stale reference is worse: pressing FG then dies with
    # "wrapped C/C++ object of type QgsRasterLayer has been deleted".
    if pre_encoded:
        say('Geo-SAM is in Pre-encoded mode: leaving the loaded feature folder alone')
    elif not _image_source_alive(sel, ras):
        if hasattr(sel, 'img_crs_manager'):
            delattr(sel, 'img_crs_manager')
            say('image source was stale, rebuilding it')
        # The plugin's _set_runtime_for_layer() starts with
        # current_runtime_layer.id(), which raises on a deleted wrapper and
        # aborts the whole re-activation. Drop the dead reference first.
        _forget_dead_raster(sel)
        wdg.LiveEncodingLayerComboBox.setLayer(ras)
        try:
            sel.on_live_encoding_layer_changed()
        except Exception as e:
            say('first activation attempt failed: %r' % e)
        if not hasattr(sel, 'img_crs_manager'):
            # The handler may skip a layer it believes is already active.
            # Force a real change: clear the combo, then select the raster.
            try:
                wdg.LiveEncodingLayerComboBox.setLayer(None)
                sel.on_live_encoding_layer_changed()
            except Exception:
                pass
            wdg.LiveEncodingLayerComboBox.setLayer(ras)
            sel.on_live_encoding_layer_changed()
    if not pre_encoded and not hasattr(sel, 'img_crs_manager'):
        raise RuntimeError('img_crs_manager was not created, the image source '
                           'did not activate')

    # Do NOT setLayer(None) first. Any trip through None drags
    # set_vector_layer -> reset_layer(None) -> _init_layer(), which calls
    # addAttributes unconditionally -> "field already exists".
    # Set it directly and call set_vector_layer() by hand: it reads
    # currentLayer(), it does not need the signal.
    wdg.MapLayerComboBox.setLayer(target)
    sel.set_vector_layer()
    if not hasattr(sel, 'polygon'):
        raise RuntimeError('Geo-SAM failed to bind the layer')
    return sel.polygon.get_layer()


def _install_hook(repo, gpkg, names, ras_name, sel, say):
    """Click a layer in the Layers panel -> Geo-SAM switches to it."""
    import qgis.utils
    from qgis.utils import iface

    view = iface.layerTreeView()
    prev = getattr(qgis.utils, '_bunjilview_layer_hook', None)
    if prev is not None:
        try:
            view.currentLayerChanged.disconnect(prev)
        except Exception:
            pass

    def on_changed(lyr):
        try:
            if lyr is None or lyr.name() not in names or not _is_site_layer(lyr, gpkg):
                return
            ras = _live_raster(ras_name)
            if hasattr(sel, 'polygon'):
                try:
                    cur = sel.polygon.get_layer()
                except RuntimeError:
                    cur = None
                if (cur is not None and cur.id() == lyr.id()
                        and (_pre_encoded_mode(sel) or _image_source_alive(sel, ras))):
                    return          # already bound and healthy: nothing to do
            if ras is None:
                iface.messageBar().pushWarning(
                    'Geo-SAM', 'orthomosaic %r is no longer in the project, '
                    're-run repair_session.py' % ras_name)
                return
            _bind(sel, ras, lyr, lambda m: None)
            _style(lyr, _color_for(lyr.name(), names))
            if not lyr.isEditable():
                lyr.startEditing()
            iface.messageBar().pushInfo(
                'Geo-SAM', 'switched to layer %s' % lyr.name())
        except Exception as e:
            iface.messageBar().pushWarning(
                'Geo-SAM', 'could not switch to %s: %s'
                % (lyr.name() if lyr else '?', e))

    view.currentLayerChanged.connect(on_changed)
    qgis.utils._bunjilview_layer_hook = on_changed

    # Also watch the project itself: if the orthomosaic is removed, drop the
    # plugin's reference before it can dangle; if it comes back, rebind the
    # current species layer so FG works again without any click.
    proj = QgsProject.instance()
    prev = getattr(qgis.utils, '_bunjilview_raster_hooks', None)
    if prev:
        for sig, fn in prev:
            try:
                sig.disconnect(fn)
            except Exception:
                pass

    def on_will_remove(ids):
        try:
            rt = getattr(sel, 'runtime_layer', None)
            if rt is not None and rt.id() in ids:
                sel.runtime_layer = None
        except RuntimeError:
            sel.runtime_layer = None

    def _rebind_to(lyr):
        try:
            if not hasattr(sel, 'polygon'):
                return
            cur = sel.polygon.get_layer()
            if cur is None or not _is_site_layer(cur, gpkg):
                return
            _bind(sel, lyr, cur, lambda m: None)
            iface.messageBar().pushInfo(
                'Geo-SAM', 'orthomosaic %s reloaded, image source rebuilt' % ras_name)
        except Exception as e:
            iface.messageBar().pushWarning(
                'Geo-SAM', 'could not rebind after the orthomosaic changed: %s' % e)

    def on_added(layers):
        # layersAdded fires after the project registered the layers, but the
        # plugin's layer combo box refreshes from the same signal and may run
        # after us, so defer one event-loop turn before touching it.
        from qgis.PyQt.QtCore import QTimer
        for lyr in layers:
            if isinstance(lyr, QgsRasterLayer) and lyr.name() == ras_name:
                QTimer.singleShot(0, lambda l=lyr: _rebind_to(l))
                return

    proj.layersWillBeRemoved.connect(on_will_remove)
    proj.layersAdded.connect(on_added)
    qgis.utils._bunjilview_raster_hooks = [
        (proj.layersWillBeRemoved, on_will_remove),
        (proj.layersAdded, on_added),
    ]
    say('hook installed: clicking a layer in the Layers panel switches Geo-SAM')


def setup(repo=REPO, site=SITE, species=SPECIES, verbose=True):
    say = (lambda m: print(m)) if verbose else (lambda m: None)
    proj = QgsProject.instance()
    gpkg = os.path.join(repo, 'data', 'labels', site, site + '.gpkg')
    # Orthomosaic: the path the pipeline recorded in site.json (it can stay
    # wherever it already is), else the default data/raw/<site>.tif.
    ortho = os.path.join(repo, 'data', 'raw', site + '.tif')
    _sj = os.path.join(repo, 'data', 'labels', site, 'site.json')
    if os.path.isfile(_sj):
        try:
            import json as _json
            _rec = _json.load(open(_sj)).get('ortho')
            if _rec and os.path.isfile(_rec):
                ortho = _rec
        except Exception:
            pass
    if not os.path.isfile(gpkg):
        raise RuntimeError('%s not found. Run scripts/init_labels_gpkg.py first.'
                           % gpkg)

    names = _species_names(repo)
    if not names:
        raise RuntimeError('config.yaml has no species under `classes`')
    if species is None:
        species = names[0]
    if species not in names:
        raise RuntimeError("'%s' is not in config.yaml `classes`. Available: %s"
                           % (species, ', '.join(names)))

    # -- load every species layer, each in its own colour --
    loaded = {}
    for name in names:
        lyr = next((l for l in proj.mapLayers().values()
                    if l.name() == name and _is_site_layer(l, gpkg)), None)
        if lyr is None:
            lyr = QgsVectorLayer(gpkg + '|layername=' + name, name, 'ogr')
            if not lyr.isValid():
                say('  skipping %s (could not open)' % name)
                continue
            proj.addMapLayer(lyr)
        _style(lyr, _color_for(name, names))
        loaded[name] = lyr
    say('loaded %d species layers, one colour each' % len(loaded))

    target = loaded.get(species)
    if target is None:
        raise RuntimeError("could not open layer '%s' in %s" % (species, gpkg))

    missing = [f for f in GEOSAM_FIELDS + BUNJIL_FIELDS
               if f not in [x.name() for x in target.fields()]]
    if missing:
        raise RuntimeError("layer '%s' is missing fields %r. Re-run "
                           "scripts/init_labels_gpkg.py." % (species, missing))
    say("layer '%s': %d fields, %d features"
        % (species, len(target.fields()), target.featureCount()))

    # -- orthomosaic --
    ras = _live_raster(site)
    if ras is None and os.path.isfile(ortho):
        ras = QgsRasterLayer(ortho, site)
        if ras.isValid():
            proj.addMapLayer(ras)
            say('loaded orthomosaic %s' % ortho)
    if ras is None:
        raise RuntimeError('no raster layer %r in the project and %s does not exist'
                           % (site, ortho))

    # Geo-SAM takes the clicked point in the PROJECT CRS and compares it with
    # the raster chip in the RASTER CRS without converting ("Point prompt lies
    # outside the chip bounds", "Bounding-box CRS is missing", and a rectangle
    # instead of a mask). A project in EPSG:4326 over a UTM ortho hits this on
    # every click, so the project CRS follows the ortho. Display only, no data
    # is changed.
    if proj.crs() != ras.crs():
        proj.setCrs(ras.crs())
        say('project CRS set to %s to match the orthomosaic (Geo-SAM needs this)'
            % ras.crs().authid())

    # -- plugin --
    geo = plugins.get('GeoSAM')
    if geo is None:
        raise RuntimeError('the GeoSAM plugin is not loaded')
    if getattr(geo, 'wdg_select', None) is None:
        geo.create_widget_selector()
        say('opened the Geo-SAM selector')
    sel = geo.wdg_select

    bound = _bind(sel, ras, target, say)
    say('image source: %s' % ('pre-encoded feature folder (loaded in the panel)'
                              if _pre_encoded_mode(sel) else 'live encoding of ' + ras.name()))
    say("Geo-SAM bound to '%s' (%d features)"
        % (bound.name() if bound else None, bound.featureCount() if bound else -1))

    # Re-apply the colours AFTER binding: Geo-SAM's show_layer() calls
    # addMapLayer and overwrites the renderer, so styling before binding is
    # wasted work.
    for name, lyr in loaded.items():
        _style(lyr, _color_for(name, names))
    say('re-applied colours to %d layers after binding' % len(loaded))

    try:
        from qgis.utils import iface
        iface.setActiveLayer(target)
        if not target.isEditable():
            target.startEditing()
        say('active layer = %s | editable = %s'
            % (target.name(), target.isEditable()))
    except Exception as e:
        say('could not enable edit mode: %r' % e)

    # Move the orthomosaic to the bottom and zoom to it while there are no
    # polygons yet. An empty layer has an empty extent, so QGIS has nothing to
    # frame, the canvas stays at planet scale and the ortho is smaller than one
    # pixel - which looks exactly like a missing image.
    try:
        from qgis.utils import iface
        root = proj.layerTreeRoot()
        node = root.findLayer(ras.id())
        if node is not None:
            if not node.isVisible():
                node.setItemVisibilityChecked(True)
            if root.children() and root.children()[-1] is not node:
                root.insertChildNode(-1, node.clone())
                root.removeChildNode(node)
        has_polygons = any(l.featureCount() > 0 for l in loaded.values())
        if not has_polygons:
            iface.mapCanvas().setDestinationCrs(ras.crs())
            iface.mapCanvas().setExtent(ras.extent())
            iface.mapCanvas().refresh()
            say('no polygons yet -> zoomed to the orthomosaic')
        else:
            say('polygons present, leaving the current view alone')
    except Exception as e:
        say('could not zoom to the orthomosaic: %r' % e)

    _install_hook(repo, gpkg, names, ras.name(), sel, say)

    say("\nReady. Draw a seed for '%s', press S, then run "
        "Scripts > Bunjilview > Propagate species from seed and pick this same "
        "layer." % species)
    say('To switch species: CLICK that layer in the Layers panel.')
    return sel


try:
    selector = setup()
except Exception as exc:
    print('SETUP FAILED: %s' % exc)
