"""
reset_site_labels.py
--------------------
WIPE every polygon of a site and start again from 9 empty species layers.

    exec(open('/path/to/segmentation_model/scripts/reset_site_labels.py').read())

Deletes:
  - data/labels/<site>/<site>.gpkg        (every polygon of every species)
  - data/labels/<site>/prototypes/        (so one-vs-rest does not learn from
                                           data you just discarded)

Kept as-is (regenerating these is very slow):
  - _patch_feats.npy, _patch_index.npy, _patch_xy.npy, _tiles.json
  - sam_candidates/
  - site.json

After wiping it recreates the gpkg with 9 empty layers using the correct
schema, then runs repair_session.py to rebuild the session and self-test.

THIS CANNOT BE UNDONE. To avoid running it by accident, CONFIRM must be True
just below.
"""
import os
import shutil
import subprocess
import time

# ------------------------------------------------------------------- config
# On another machine, do NOT edit this file. Set the 3 variables below ONCE
# per QGIS session, before running any script (see README.md):
#
#   import qgis.utils
#   qgis.utils.BV_REPO   = r'D:\path\to\segmentation_model'
#   qgis.utils.BV_SITE   = 'site_name'
#   qgis.utils.BV_PYTHON = r'C:\...\envs\bunjilview\python.exe'   # optional
#
# If BV_PYTHON is left empty the script reads it from
# data/labels/<site>/site.json.
DEFAULT_REPO = '/Users/huydinh/Desktop/Home/Bunjilview/segmentation_model'
DEFAULT_SITE = 'test1'
DEFAULT_PYTHON = '/opt/homebrew/Caskroom/miniconda/base/envs/bunjilview/bin/python'


def _cfg():
    import json
    import qgis.utils as _qu
    repo = (getattr(_qu, 'BV_REPO', '') or DEFAULT_REPO).rstrip('/\\')
    site = getattr(_qu, 'BV_SITE', '') or DEFAULT_SITE
    py = getattr(_qu, 'BV_PYTHON', '')
    if not py:
        sj = os.path.join(repo, 'data', 'labels', site, 'site.json')
        if os.path.isfile(sj):
            try:
                py = json.load(open(sj)).get('venv_python', '') or ''
            except Exception:
                py = ''
    return repo, site, (py or DEFAULT_PYTHON)


REPO, SITE, VENV_PYTHON = _cfg()


def _child_env(venv_python):
    """Environment for the venv interpreter with QGIS's own Python scrubbed.
    QGIS exports PYTHONHOME/PYTHONPATH/GDAL_DATA/PROJ_LIB for its bundled
    copies; a conda interpreter inheriting them loads the wrong stdlib and
    the wrong proj.db. Conda on Windows also needs Library\\bin on PATH."""
    env = dict(os.environ)
    for k in ('PYTHONHOME', 'PYTHONPATH', 'PYTHONSTARTUP', 'PYTHONNOUSERSITE',
              'GDAL_DATA', 'GDAL_DRIVER_PATH', 'PROJ_LIB', 'PROJ_DATA',
              'GEOTIFF_CSV', 'QT_PLUGIN_PATH', 'QGIS_PREFIX_PATH'):
        env.pop(k, None)
    env['PYTHONIOENCODING'] = 'utf-8'
    root = os.path.dirname(os.path.abspath(venv_python))
    if os.path.basename(root).lower() == 'bin':
        root = os.path.dirname(root)
    extra = [d for d in (root, os.path.join(root, 'Library', 'bin'),
                         os.path.join(root, 'Scripts'), os.path.join(root, 'bin'))
             if os.path.isdir(d)]
    env['PATH'] = os.pathsep.join(extra + [env.get('PATH', '')])
    for var, rel in (('PROJ_LIB', ('Library', 'share', 'proj')),
                     ('PROJ_LIB', ('share', 'proj')),
                     ('GDAL_DATA', ('Library', 'share', 'gdal')),
                     ('GDAL_DATA', ('share', 'gdal'))):
        d = os.path.join(root, *rel)
        if var not in env and os.path.isdir(d):
            env[var] = d
    return env

CONFIRM = True           # set to False to block accidental runs


def reset(repo=REPO, site=SITE, venv_python=VENV_PYTHON):
    if not CONFIRM:
        print('CONFIRM = False, doing nothing. Set it to True if you really want to wipe.')
        return

    from qgis.core import QgsProject
    d = os.path.join(repo, 'data/labels', site)
    gpkg = os.path.join(d, site + '.gpkg')

    # 1. release every QGIS handle before touching the file
    ids = []
    for lid, l in QgsProject.instance().mapLayers().items():
        try:
            if site + '.gpkg' in l.source():
                ids.append(lid)
        except Exception:
            pass
    for lid in ids:
        l = QgsProject.instance().mapLayer(lid)
        if l is not None and l.isEditable():
            l.rollBack()
    if ids:
        QgsProject.instance().removeMapLayers(ids)
    print('removed %d layer(s) from the project' % len(ids))

    # 2. delete the gpkg and the prototypes
    for suffix in ('', '-wal', '-shm', '-journal'):
        p = gpkg + suffix
        if os.path.exists(p):
            os.remove(p)
            print('deleted %s' % os.path.basename(p))
    proto = os.path.join(d, 'prototypes')
    if os.path.isdir(proto):
        shutil.rmtree(proto)
        print('deleted prototypes/')

    # 3. recreate the 9 empty layers
    p = subprocess.run([venv_python, 'scripts/init_labels_gpkg.py',
                        '--config', 'config.yaml', '--site', site],
                       cwd=repo, capture_output=True, text=True,
                       encoding='utf-8', errors='replace',
                       env=_child_env(venv_python))
    print('\n--- init_labels_gpkg (exit=%s) ---' % p.returncode)
    print(p.stdout.strip())
    if p.returncode != 0:
        print(p.stderr[-1500:])
        raise RuntimeError('failed to recreate the gpkg')

    # 4. rebuild the session + self-test
    print('\n--- rebuilding the session ---')
    exec(open(os.path.join(repo, 'scripts/repair_session.py')).read(), {})


reset()
