"""
test_pipeline.py
----------------
End-to-end test suite, run it in the QGIS Python Console:

    exec(open('/path/to/segmentation_model/scripts/test_pipeline.py').read())

It exercises the whole workflow:
  A. Patch the plugin + setup, bind to EVERY species layer (all 9)
  B. Draw a polygon into every layer through Geo-SAM's real save path, and
     check the values land in the right columns (no positional shift)
  C. Editing: delete some, add some back
  D. Propagation
  E. Propagate AGAIN on the same layer -> must not duplicate polygons
  F. Delete a few auto polygons and propagate again -> must pick them back up

The test cleans up after itself: every polygon it creates is deleted at the
end, and your data comes back exactly as it was before the run.

The report is written to <repo>/test_report.txt and printed to the console.
"""
import io
import os
import subprocess
import time
import traceback

from qgis.core import QgsApplication, QgsProject
from qgis.utils import iface, plugins

# ------------------------------------------------------------------- config
# On another machine, do NOT edit this file. Set the 3 variables below ONCE
# per QGIS session, before running any script (see README.md):
#
#   import qgis.utils
#   qgis.utils.BV_REPO   = r'D:\path\to\segmentation_model'
#   qgis.utils.BV_SITE   = 'site_name'
#   qgis.utils.BV_PYTHON = r'C:\...\envs\bunjilview\python.exe'   # optional
#
# If BV_PYTHON is left empty the script reads it from
# data/labels/<site>/site.json.
DEFAULT_REPO = '/Users/huydinh/Desktop/Home/Bunjilview/segmentation_model'
DEFAULT_SITE = 'test1'
DEFAULT_PYTHON = '/opt/homebrew/Caskroom/miniconda/base/envs/bunjilview/bin/python'


def _cfg():
    import json
    import qgis.utils as _qu
    repo = (getattr(_qu, 'BV_REPO', '') or DEFAULT_REPO).rstrip('/\\')
    site = getattr(_qu, 'BV_SITE', '') or DEFAULT_SITE
    py = getattr(_qu, 'BV_PYTHON', '')
    if not py:
        sj = os.path.join(repo, 'data', 'labels', site, 'site.json')
        if os.path.isfile(sj):
            try:
                py = json.load(open(sj)).get('venv_python', '') or ''
            except Exception:
                py = ''
    return repo, site, (py or DEFAULT_PYTHON)


REPO, SITE, VENV_PYTHON = _cfg()
REPORT = os.path.join(REPO, 'test_report.txt')


def _child_env(venv_python):
    """Environment for the venv interpreter with QGIS's own Python scrubbed.
    QGIS exports PYTHONHOME/PYTHONPATH/GDAL_DATA/PROJ_LIB for its bundled
    copies; a conda interpreter inheriting them loads the wrong stdlib and
    the wrong proj.db. Conda on Windows also needs Library\\bin on PATH."""
    env = dict(os.environ)
    for k in ('PYTHONHOME', 'PYTHONPATH', 'PYTHONSTARTUP', 'PYTHONNOUSERSITE',
              'GDAL_DATA', 'GDAL_DRIVER_PATH', 'PROJ_LIB', 'PROJ_DATA',
              'GEOTIFF_CSV', 'QT_PLUGIN_PATH', 'QGIS_PREFIX_PATH'):
        env.pop(k, None)
    env['PYTHONIOENCODING'] = 'utf-8'
    root = os.path.dirname(os.path.abspath(venv_python))
    if os.path.basename(root).lower() == 'bin':
        root = os.path.dirname(root)
    extra = [d for d in (root, os.path.join(root, 'Library', 'bin'),
                         os.path.join(root, 'Scripts'), os.path.join(root, 'bin'))
             if os.path.isdir(d)]
    env['PATH'] = os.pathsep.join(extra + [env.get('PATH', '')])
    for var, rel in (('PROJ_LIB', ('Library', 'share', 'proj')),
                     ('PROJ_LIB', ('share', 'proj')),
                     ('GDAL_DATA', ('Library', 'share', 'gdal')),
                     ('GDAL_DATA', ('share', 'gdal'))):
        d = os.path.join(root, *rel)
        if var not in env and os.path.isdir(d):
            env[var] = d
    return env


def _dup_iou():
    try:
        import yaml
        with open(os.path.join(REPO, 'config.yaml')) as f:
            return float(yaml.safe_load(f)['propagate']['match']['dup_iou'])
    except Exception:
        return 0.30


DUP_IOU = _dup_iou()

_out = io.StringIO()
_results = []
_logged = []


def say(m=''):
    _out.write(str(m) + '\n')


def check(name, cond, detail=''):
    _results.append((name, bool(cond), detail))
    say('%-4s  %-54s %s' % ('PASS' if cond else 'FAIL', name, detail))
    return bool(cond)


def _on_log(message, tag, level):
    if level >= 2:                       # Warning and above
        _logged.append('[%s] %s' % (tag, message))


class _SkipRest(Exception):
    """Raised to skip the propagation sections when there is nothing to learn from."""


def _species_names():
    import yaml
    with open(os.path.join(REPO, 'config.yaml')) as f:
        cfg = yaml.safe_load(f)
    return [v for _, v in sorted(cfg['classes'].items(), key=lambda kv: int(kv[0]))
            if v and v != 'None']


def _layer(name):
    return next((l for l in QgsProject.instance().mapLayers().values()
                 if l.name() == name and SITE + '.gpkg' in l.source()), None)


def _fids(name):
    l = _layer(name)
    return set(f.id() for f in l.getFeatures()) if l else set()


def _square(lyr, dx, dy, size=6.0):
    """A small square inside the layer extent, offset by dx/dy so they do not
    overlap each other."""
    e = lyr.extent() if lyr.featureCount() else iface.mapCanvas().extent()
    x0 = e.xMinimum() + 10 + dx
    y0 = e.yMinimum() + 10 + dy
    ring = [[x0, y0], [x0 + size, y0], [x0 + size, y0 + size], [x0, y0 + size],
            [x0, y0]]
    return {'type': 'Feature', 'properties': {},
            'geometry': {'type': 'Polygon', 'coordinates': [ring]}}


def _draw(sel, lyr, gj):
    """Draw through exactly the Geo-SAM path used when you press S."""
    sel.polygon.add_geojson_feature_to_layer(gj, 0, ['fgpt'], max_object_mode=False)
    sel.polygon.commit_changes()
    lyr.reload()


def _run(args, tag):
    p = subprocess.run(args, cwd=REPO, capture_output=True, text=True,
                       encoding='utf-8', errors='replace',
                       env=_child_env(args[0]))
    say('    $ %s' % ' '.join(a.split('/')[-1] for a in args[:3]))
    for ln in p.stdout.strip().splitlines():
        if any(k in ln for k in ('ADDED', 'seeds:', 'other species', 'passed',
                                 'skipped', 'Error', 'error')):
            say('      %s' % ln.strip())
    if p.returncode != 0:
        say('      stderr: %s' % p.stderr.strip()[-600:])
    return p.returncode


def main():
    t0 = time.time()
    gpkg = os.path.join(REPO, 'data/labels', SITE, SITE + '.gpkg')
    names = _species_names()
    QgsApplication.messageLog().messageReceived.connect(_on_log)
    baseline = {}

    try:
        say('=' * 78)
        say('PIPELINE TEST SUITE  -  %s' % time.strftime('%Y-%m-%d %H:%M:%S'))
        say('=' * 78)

        # ---------------- A. patch plugin + setup ----------------
        say('\n--- A. Patch the plugin, run setup, bind to every layer ---')
        ns = {}
        exec(open(os.path.join(REPO, 'scripts/patch_geosam_fields.py')).read(), ns)
        import qgis.utils
        qgis.utils.reloadPlugin('GeoSAM')
        ns = {}
        exec(open(os.path.join(REPO, 'qgis/setup_geosam_session.py')).read(), ns)
        sel = plugins.get('GeoSAM').wdg_select
        check('A0 setup finished, Geo-SAM has a polygon tool',
              hasattr(sel, 'polygon'))

        for name in names:
            baseline[name] = _fids(name)

        _logged.clear()
        bad = []
        for name in names:
            lyr = _layer(name)
            if lyr is None:
                bad.append('%s: could not load' % name)
                continue
            iface.setActiveLayer(lyr)          # exactly like a user click
            got = sel.polygon.get_layer()
            if got is None or got.name() != name:
                bad.append('%s: bound to %r' % (name, got.name() if got else None))
            elif not lyr.isEditable():
                bad.append('%s: did not enter edit mode' % name)
        check('A1 binds to all %d layers' % len(names), not bad, '; '.join(bad))

        field_errs = [m for m in _logged if 'already exists' in m]
        check('A2 no more "field already exists" errors', not field_errs,
              field_errs[0][:90] if field_errs else '')

        # ---------------- B. draw into every layer ----------------
        say('\n--- B. Draw a polygon into every layer, check the columns ---')
        drawn = {}
        bad = []
        for i, name in enumerate(names):
            lyr = _layer(name)
            iface.setActiveLayer(lyr)
            before = lyr.featureCount()
            _draw(sel, lyr, [_square(lyr, i * 12.0, 0.0)])
            after = lyr.featureCount()
            if after != before + 1:
                bad.append('%s: %d -> %d' % (name, before, after))
                continue
            new = max(_fids(name) - baseline[name])
            drawn[name] = new
            f = next(x for x in lyr.getFeatures() if x.id() == new)
            probs = []
            if not isinstance(f.id(), int):
                probs.append('fid is not a number')
            if not str(f['group_ulid']) or str(f['group_ulid']) == 'NULL':
                probs.append('group_ulid empty')
            if not (30 < (f['Area'] or 0) < 40):
                probs.append('Area=%r (expected ~36)' % f['Area'])
            if str(f['N_FG']) != '1':
                probs.append('N_FG=%r' % f['N_FG'])
            if probs:
                bad.append('%s: %s' % (name, ', '.join(probs)))
        check('B1 draws into all %d layers' % len(names), len(drawn) == len(names),
              '%d/%d' % (len(drawn), len(names)))
        check('B2 values land in the right columns (no positional shift)', not bad,
              '; '.join(bad)[:150])

        # ---------------- C. editing: delete, add back ----------------
        say('\n--- C. Editing: delete some, add some back ---')
        probe = names[0]
        lyr = _layer(probe)
        iface.setActiveLayer(lyr)
        n0 = lyr.featureCount()
        lyr.dataProvider().deleteFeatures([drawn[probe]])
        lyr.reload()
        ok_del = lyr.featureCount() == n0 - 1
        drawn.pop(probe, None)
        check('C1 delete a polygon', ok_del, '%d -> %d' % (n0, lyr.featureCount()))

        n1 = lyr.featureCount()
        _draw(sel, lyr, [_square(lyr, 200.0, 0.0), _square(lyr, 212.0, 0.0)])
        ok_add = lyr.featureCount() == n1 + 2
        check('C2 add 2 polygons at once', ok_add,
              '%d -> %d' % (n1, lyr.featureCount()))

        extra = sorted(_fids(probe) - baseline[probe])
        lyr.dataProvider().deleteFeatures(extra)
        lyr.reload()
        check('C3 cleaned up, back to the original count',
              lyr.featureCount() == len(baseline[probe]),
              '%d features' % lyr.featureCount())

        # ---------------- D/E/F. propagation ----------------
        say('\n--- D. Propagate on a layer that already has seeds ---')
        for name in list(drawn):        # remove the test squares before propagating
            l2 = _layer(name)
            l2.dataProvider().deleteFeatures([drawn[name]])
            l2.reload()
        drawn.clear()

        # Propagate on the species that has the most hand-drawn polygons in
        # the BASELINE data: a layer with no seed makes propagate.py refuse,
        # correctly, and that would be a false failure of this suite.
        def _hand_drawn(name):
            l = _layer(name)
            return 0 if l is None else sum(
                1 for f in l.getFeatures()
                if f.id() in baseline[name] and str(f['source']) != 'auto')
        seeded = sorted(((_hand_drawn(n), n) for n in names), reverse=True)
        if not seeded or seeded[0][0] == 0:
            say('    no species layer holds a hand-drawn seed on this site, so')
            say('    D, E and F cannot run. Draw one seed with Geo-SAM and rerun.')
            for k in ('D1 propagate finished (exit 0)', 'D2 no existing polygon was lost',
                      'E1 second run finished', 'E3 no duplicate polygons',
                      'F1 delete auto polygons', 'F2 re-run finished',
                      'F3 re-run after deletion lost nothing'):
                _results.append((k + '  [SKIPPED: no seeds]', True, ''))
                say('SKIP  %s' % k)
            raise _SkipRest()
        target = seeded[0][1]
        say('    target: %s (%d hand-drawn seed polygons)' % (target, seeded[0][0]))
        lyr = _layer(target)
        if lyr.isEditable():
            lyr.commitChanges()
        n_before = lyr.featureCount()
        rc = _run([VENV_PYTHON, 'src/propagate.py', '--config', 'config.yaml',
                   '--site', SITE, '--layer', gpkg, '--species', target,
                   '--threshold', '0.60', '--margin', '0.05'], 'propagate')
        lyr.reload()
        n_after = lyr.featureCount()
        check('D1 propagate finished (exit 0)', rc == 0, 'exit=%s' % rc)
        check('D2 no existing polygon was lost', n_after >= n_before,
              '%d -> %d' % (n_before, n_after))

        say('\n--- E. Propagate AGAIN ---')
        say('    (By design, seed_sources counts auto polygons as seeds too, so')
        say('     a second run can add MORE than the first while the prototype')
        say('     widens, then saturates. The property that must hold is that')
        say('     no two polygons overlap; the per-run counts are reported only.)')
        added_1 = n_after - n_before
        n2 = lyr.featureCount()
        rc = _run([VENV_PYTHON, 'src/propagate.py', '--config', 'config.yaml',
                   '--site', SITE, '--layer', gpkg, '--species', target,
                   '--threshold', '0.60', '--margin', '0.05'], 'propagate run 2')
        lyr.reload()
        n3 = lyr.featureCount()
        added_2 = n3 - n2
        check('E1 second run finished', rc == 0, 'exit=%s' % rc)
        say('INFO  E2 run 1 added %d, run 2 added %d (not a pass/fail check)'
            % (added_1, added_2))

        worst, pair = 0.0, None
        feats = [(f.id(), f.geometry()) for f in lyr.getFeatures()
                 if f.geometry() and not f.geometry().isEmpty()]
        for i in range(len(feats)):
            for j in range(i + 1, len(feats)):
                ga, gb = feats[i][1], feats[j][1]
                if not ga.boundingBoxIntersects(gb):
                    continue
                inter = ga.intersection(gb)
                if inter.isEmpty():
                    continue
                union = ga.area() + gb.area() - inter.area()
                iou = inter.area() / union if union > 0 else 0.0
                if iou > worst:
                    worst, pair = iou, (feats[i][0], feats[j][0])
        check('E3 no duplicate polygons (IoU < %.2f)' % DUP_IOU,
              worst < DUP_IOU,
              'largest IoU %.3f %s across %d polygons' % (worst, pair or '', len(feats)))

        say('\n--- F. Delete a few auto polygons, then propagate again ---')
        # Only delete polygons THIS TEST created. Touching the original data
        # would lose it for good: the cleanup step cannot resurrect a deleted
        # feature.
        autos = [f.id() for f in lyr.getFeatures()
                 if str(f['source']) == 'auto' and f.id() not in baseline[target]]
        victims = autos[:3]
        n4 = lyr.featureCount()
        lyr.dataProvider().deleteFeatures(victims)
        lyr.reload()
        check('F1 deleted %d auto polygons' % len(victims),
              lyr.featureCount() == n4 - len(victims),
              '%d -> %d' % (n4, lyr.featureCount()))
        rc = _run([VENV_PYTHON, 'src/propagate.py', '--config', 'config.yaml',
                   '--site', SITE, '--layer', gpkg, '--species', target,
                   '--threshold', '0.60', '--margin', '0.05'],
                  'propagate after deletion')
        lyr.reload()
        n5 = lyr.featureCount()
        check('F2 re-run finished', rc == 0, 'exit=%s' % rc)
        # There is no memory of deletions anywhere, so a deleted auto polygon
        # is eligible again. Whether it actually comes back depends on the
        # remaining seeds still supporting it, so only "nothing lost" is a
        # hard requirement; the recovered count is reported.
        check('F3 re-run after deletion lost nothing', n5 >= n4 - len(victims),
              '%d -> %d (deleted %d, recovered %d)'
              % (n4 - len(victims), n5, len(victims), n5 - (n4 - len(victims))))

    except _SkipRest:
        pass
    except Exception:
        say('\nEXCEPTION:\n' + traceback.format_exc())
        _results.append(('exception while running the tests', False, ''))

    # ---------------- cleanup ----------------
    try:
        say('\n--- Cleanup: restore the data to its original state ---')
        for name, fids0 in baseline.items():
            l = _layer(name)
            if l is None:
                continue
            if l.isEditable():
                l.commitChanges()
            extra = sorted(set(f.id() for f in l.getFeatures()) - fids0)
            if extra:
                l.dataProvider().deleteFeatures(extra)
                l.reload()
            lost = len(fids0) - len(set(f.id() for f in l.getFeatures()) & fids0)
            say('  %-26s %d features (originally %d)%s%s'
                % (name, l.featureCount(), len(fids0),
                   '  deleted %d' % len(extra) if extra else '',
                   '   <<< LOST %d ORIGINAL FEATURES' % lost if lost else ''))
            if lost:
                _results.append(('cleanup lost %d original feature(s) of %s'
                                 % (lost, name), False, ''))
    except Exception:
        say('cleanup error:\n' + traceback.format_exc())

    try:
        QgsApplication.messageLog().messageReceived.disconnect(_on_log)
    except Exception:
        pass

    npass = sum(1 for _, ok, _ in _results if ok)
    say('\n' + '=' * 78)
    say('RESULT: %d/%d PASS   (%.1fs)' % (npass, len(_results), time.time() - t0))
    for name, ok, detail in _results:
        if not ok:
            say('  FAIL  %s  %s' % (name, detail))
    say('=' * 78)

    open(REPORT, 'w').write(_out.getvalue())
    print(_out.getvalue())
    print('report: %s' % REPORT)


main()
